#pragma once
#include "esp_bt.h"
#include "RawView.h"

//! source: https://www.lisha.ufsc.br/teaching/shi/ine5346-2003-1/work/bluetooth/hci_commands.html

#define _MK_OPCODE(ocf, ogf) (uint16_t)((ogf << 10) | (ocf & 0x3f))
#define PACKED_STRUCT struct __attribute__((packed))

#define HCI_OGF_LinkControlCommands 0x01
#define HCI_OGF_PolicyCommand 0x02
#define HCI_OGF_HostControllerandBasebandCommands 0x03

enum HCI_PolicyCommands
{
    HCI_PC_Hold_Mode = 0x0001,                  // Command to place the current or remote device into the Hold mode state.
    HCI_PC_Sniff_Mode = 0x0003,                 // Command to place the current or remote device into the Sniff mode state.
    HCI_PC_Exit_Sniff_Mode = 0x0004,            // Command to exit the current or remote device from the Sniff mode state.
    HCI_PC_Park_Mode = 0x0005,                  // Command to place the current or remote device into the Park mode state.
    HCI_PC_Exit_Park_Mode = 0x0006,             // Command to exit the current or remote device from the Park mode state.
    HCI_PC_QoS_Setup = 0x0007,                  // Command to setup the Quality of Service parameters of the device.
    HCI_PC_Role_Discovery = 0x0009,             // Command to determine the role of the device for a particular connection.
    HCI_PC_Switch_Role = 0x000B,                // Command to allow the device to switch roles for a particular connection.
    HCI_PC_Read_Link_Policy_Settings = 0x000C,  // Command to determine the link policy that the LM can use to establish connections.
    HCI_PC_Write_Link_Policy_Settings = 0x000D, // Command to set the link policy that the LM can use for a particular connection.
};

enum HCI_LinkControlCommands
{
    HCI_LCC_Inquiry = 0x0001,                         // Command used to enter Inquiry mode where it discovers other Bluetooth devices.
    HCI_LCC_Inquiry_Cancel = 0x0002,                  // Command to cancel the Inquiry mode in which the Bluetooth device is in.
    HCI_LCC_Periodic_Inquiry_Mode = 0x0003,           // Command to set the device to enter Inquiry modes periodically according to the time interval set.
    HCI_LCC_Exit_Periodic_Inquiry_Mode = 0x0004,      // Command to exit the periodic Inquiry mode
    HCI_LCC_Create_Connection = 0x0005,               // Command to create an ACL connection to the device specified by the BD_ADDR in the parameters.
    HCI_LCC_Disconnect = 0x0006,                      // Command to terminate the existing connection to a device
    HCI_LCC_Add_SCO_Connection = 0x0007,              // Create an SCO connection defined by the connection handle parameters.
    HCI_LCC_Accept_Connection_Request = 0x0009,       // Command to accept a new connection request
    HCI_LCC_Reject_Connection_Request = 0x000A,       // Command to reject a new connection request
    HCI_LCC_Link_Key_Request_Reply = 0x000B,          // Reply command to a link key request event sent from controller to the host
    HCI_LCC_Link_Key_Request_Negative_Reply = 0x000C, // Reply command to a link key request event from the controller to the host if there is no link key associated with the connection.
    HCI_LCC_PIN_Code_Request_Reply = 0x000D,          // Reply command to a PIN code request event sent from a controller to the host.
    HCI_LCC_PIN_Code_Request_Negative_Reply = 0x000E, // Reply command to a PIN code request event sent from the controller to the host if there is no PIN associated with the connection.
    HCI_LCC_Change_Connection_Packet_Type = 0x000F,   // Command to change the type of packets to be sent for an existing connection.
    HCI_LCC_Authentication_Requested = 0x0011,        // Command to establish authentication between two devices specified by the connection handle.
    HCI_LCC_Set_Connection_Encryption = 0x0013,       // Command to enable or disable the link level encryption.
    HCI_LCC_Change_Connection_Link_Key = 0x0015,      // Command to force the change of a link key to a new one between two connected devices.
    HCI_LCC_Master_Link_Key = 0x0017,                 // Command to force two devices to use the master's link key temporarily.
    HCI_LCC_Remote_Name_Request = 0x0019,             // Command to determine the user friendly name of the connected device.
    HCI_LCC_Read_Remote_Supported_Features = 0x001B,  // Command to determine the features supported by the connected device.
    HCI_LCC_Read_Remote_Version_Information = 0x001D, // Command to determine the version information of the connected device.
    HCI_LCC_Read_Clock_Offset = 0x001F,               // Command to read the clock offset of the remote device.
};

enum HCI_HostCtrlr_BasebandCommands
{
    Set_Event_Mask = 0x0001,                           // Command to set which events are generated by the HCI for the host.
    Reset = 0x0003,                                    // Command to reset the host controller, link manager and the radio module.
    Set_Event_Filter = 0x0005,                         // Command used by host to set the different types of event filters that the host needs to receive.
    Flush = 0x0008,                                    // Command used to flush all pending data packets for transmission for a particular connection handle.
    Read_PIN_Type = 0x0009,                            // Command used by host to determine if the link manager assumes that the host requires a variable PIN type or fixed PIN code. PIN is used during pairing.
    Write_PIN_Type = 0x000A,                           // Command used by host to write to the host controller on the PIN type supported by the host.
    Create_New_Unit_Key = 0x000B,                      // Command used to create a new unit key.
    Read_Stored_Link_Key = 0x000D,                     // Command to read the link key stored in the host controller.
    Write_Stored_Link_Key = 0x0011,                    // Command to write the link key to the host controller.
    Delete_Stored_Link_Key = 0x0012,                   // Command to delete a stored link key in the host controller.
    Change_Local_Name = 0x0013,                        // Command to modify the user friendly name of the device.
    Read_Local_Name = 0x0014,                          // Command to read the user friendly name of the device.
    Read_Connection_Accept_Timeout = 0x0015,           // Command to determine the timeout session before the host denies and rejects a new connection request.
    Write_Connection_Accept_Timeout = 0x0016,          // Command to set the timeout session before a device can deny or reject a connection request.
    Read_Page_Timeout = 0x0017,                        // Command to read the timeout value where a device will wait for a connection acceptance before sending a connection failure is returned.
    Write_Page_Timeout = 0x0018,                       // Command to write the timeout value where a device will wait for a connection acceptance before sending a connection failure is returned.
    Read_Scan_Enable = 0x0019,                         // Command to read the status of the Scan_Enable configuration.
    Write_Scan_Enable = 0x001A,                        // Command to set the status of the Scan_Enable configuration.
    Read_Page_Scan_Activity = 0x001B,                  // Command to read the value of the Page_Scan_Interval and Page_Scan_Window configurations.
    Write_Page_Scan_Activity = 0x001C,                 // Command to write the value of the Page_Scan_Interval and Page_Scan_Window configurations.
    Read_Inquiry_Scan_Activity = 0x001D,               // Command to read the value of the Inquiry_Scan_Interval and Inquiry_Scan_Window configurations.
    Write_Inquiry_Scan_Activity = 0x001E,              // Command to set the value of the Inquiry_Scan_Interval and Inquiry_Scan_Window configurations.
    Read_Authentication_Enable = 0x001F,               // Command to read the Authentication_Enable parameter.
    Write_Authentication_Enable = 0x0020,              // Command to set the Authentication_Enable parameter.
    Read_Encryption_Mode = 0x0021,                     // Command to read the Encryption_Mode parameter.
    Write_Encryption_Mode = 0x0022,                    // Command to write the Encryption_Mode parameter.
    Read_Class_Of_Device = 0x0023,                     // Command to read the Class_Of_Device parameter.
    Write_Class_Of_Device = 0x0024,                    // Command to set the Class_Of_Device parameter.
    Read_Voice_Setting = 0x0025,                       // Command to read the Voice_Setting parameter. Used for voice connections.
    Write_Voice_Setting = 0x0026,                      // Command to set the Voice_Setting parameter. Used for voice connections.
    Read_Automatic_Flush_Timeout = 0x0027,             // Command to read the Flush_Timeout parameter. Used for ACL connections only.
    Write_Automatic_Flush_Timeout = 0x0028,            // Command to set the Flush_Timeout parameter. Used for ACL connections only.
    Read_Num_Broadcast_Retransmissions = 0x0029,       // Command to read the number of time a broadcast message is retransmitted.
    Write_Num_Broadcast_Retransmissions = 0x002A,      // Command to set the number of time a broadcast message is retransmitted.
    Read_Hold_Mode_Activity = 0x002B,                  // Command to set the Hold_Mode activity to instruct the device to perform an activity during hold mode.
    Write_Hold_Mode_Activity = 0x002C,                 // Command to set the Hold_Mode_Activity parameter.
    Read_Transmit_Power_Level = 0x002D,                // Command to read the power level required for transmission for a connection handle.
    Read_SCO_Flow_Control_Enable = 0x002E,             // Command to check the current status of the flow control for the SCO connection.
    Write_SCO_Flow_Control_Enable = 0x002F,            // Command to set the status of the flow control for a connection handle.
    Set_Host_Controller_To_Host_Flow_Control = 0x0031, // Command to set the flow control from the host controller to host in on or off state.
    Host_Buffer_Size = 0x0033,                         // Command set by host to inform the host controller of the buffer size of the host for ACL and SCO connections.
    Host_Number_Of_Completed_Packets = 0x0035,         // Command set from host to host controller when it is ready to receive more data packets.
    Read_Link_Supervision_Timeout = 0x0036,            // Command to read the timeout for monitoring link losses.
    Write_Link_Supervision_Timeout = 0x0037,           // Command to set the timeout for monitoring link losses.
    Read_Number_Of_Supported_IAC = 0x0038,             // Command to read the number of IACs that the device can listen on during Inquiry access.
    Read_Current_IAC_LAP = 0x0039,                     // Command to read the LAP for the current IAC.
    Write_Current_IAC_LAP = 0x003A,                    // Command to set the LAP for the current IAC.
    Read_Page_Scan_Period_Mode = 0x003B,               // Command to read the timeout session of a page scan.
    Write_Page_Scan_Period_Mode = 0x003C,              // Command to set the timeout session of a page scan.
    Read_Page_Scan_Mode = 0x003D,                      // Command to read the default Page scan mode.
    Write_Page_Scan_Mode = 0x003E,                     // Command to set the default page scan mode.
};

enum HCIPacketType : uint8_t
{
    HCI_Command_Packet = 0x01,           // Command 	        0x01
    HCI_Asynchronous_Data_Packet = 0x02, // Asynchronous Data 	0x02
    HCI_Synchronous_Data_Packet = 0x03,  // Synchronous Data 	0x03
    HCI_Event_Packet = 0x04,             // Event 	            0x04
    HCI_Extended_Command = 0x09,         // Extended Command 	0x09
};

enum HCIEventCode : uint8_t
{
    HCI_EC_BT_Inquiry_Complete = 0x01,
    HCI_EC_BT_Inquiry_Result = 0x02,
    HCI_EC_BT_Connection_Complete = 0x03,
    HCI_EC_BT_Connection_Request = 0x04,
    HCI_EC_BT_Disconnection_Complete = 0x05,
    HCI_EC_BT_Authentication_Complete = 0x06,
    HCI_EC_BT_Remote_Name_Request_Complete = 0x07,
    HCI_EC_BT_Encryption_Change = 0x08,
    HCI_EC_BT_Change_Connection_Link_Key_Complete = 0x09,
    HCI_EC_BT_Master_Link_Key_Complete = 0x0A,
    HCI_EC_BT_Read_Remote_Supported_Features_Complete = 0x0B,
    HCI_EC_BT_Read_Remote_Version_Information_Complete = 0x0C,
    HCI_EC_BT_QoS_Setup_Complete = 0x0D,
    HCI_EC_BT_Command_Complete = 0x0E,
    HCI_EC_BT_Command_Status = 0x0F,
    HCI_EC_BT_Hardware_Error = 0x10,
    HCI_EC_BT_Flush_Occurred = 0x11,
    HCI_EC_BT_Role_Change  = 0x12,
    HCI_EC_BT_Number_Of_Completed_Packets = 0x13,
    HCI_EC_BT_Mode_Change = 0x14,
    HCI_EC_BT_Return_Link_Keys = 0x15,
    HCI_EC_BT_PIN_Code_Request = 0x16,
    HCI_EC_BT_Link_Key_Request = 0x17,
    HCI_EC_BT_Link_Key_Notification = 0x18,
    HCI_EC_BT_Loopback_Command = 0x19,
    HCI_EC_BT_Data_Buffer_Overflow = 0x1A,
    HCI_EC_BT_Max_Slots_Change = 0x1B,
    HCI_EC_BT_Read_Clock_Offset_Complete = 0x1C,
    HCI_EC_BT_Connection_Packet_Type_Changed = 0x1D,
    HCI_EC_BT_Encryption_Key_Refresh_Complete = 0x30,
    HCI_EC_BT_Authenticated_Payload_Timeout_Expired = 0x57,
};

void HCIPacket_send_Command(int commandField, int groupField, void *data = nullptr, size_t len = 0);
void HCIPacket_send_Event(int eventCode, void *data = nullptr, size_t len = 0);
void HCIPacket_send_AsyncData(int connectionHandle, int packetBoundaryFlags, int broadcastFlags, void *data = nullptr, size_t len = 0);
void HCIPacket_send_SyncData(int connectionHandle, int packetStatusFlags, void *data = nullptr, size_t len = 0);
void HCIPacket_send_ExtendedCommand(int LSB_opcode, int MSB_opcode, int LSB_len, int MSB_len, void *data = nullptr, size_t len = 0);

#ifndef HCI_BUFFER_CAP
#define HCI_BUFFER_CAP 64
#endif
#define CHCK_BUFOVRFLW(t) static_assert(HCI_BUFFER_CAP > sizeof(t), "T exceeds BUFFER_CAP")

template <class T>
void HCIPacket_send_Command(int commandField, int groupField, T data)
{
    CHCK_BUFOVRFLW(T);
    HCIPacket_send_Command(commandField, groupField, &data, sizeof(T));
}
template <class T>
void HCIPacket_send_Event(int eventCode, T data)
{
    CHCK_BUFOVRFLW(T);
    HCIPacket_send_Event(eventCode, &data, sizeof(T));
}
template <class T>
void HCIPacket_send_AsyncData(int connectionHandle, int packetBoundaryFlags, int broadcastFlags, T data)
{
    CHCK_BUFOVRFLW(T);
    HCIPacket_send_AsyncData(connectionHandle, packetBoundaryFlags, broadcastFlags, &data, sizeof(T));
}
template <class T>
void HCIPacket_send_SyncData(int connectionHandle, int packetStatusFlags, T data)
{
    CHCK_BUFOVRFLW(T);
    HCIPacket_send_SyncData(connectionHandle, packetStatusFlags, &data, sizeof(T));
}
template <class T>
void HCIPacket_send_ExtendedCommand(int LSB_opcode, int MSB_opcode, int LSB_len, int MSB_len, T data)
{
    CHCK_BUFOVRFLW(T);
    HCIPacket_send_ExtendedCommand(LSB_opcode, MSB_opcode, LSB_len, MSB_len, &data, sizeof(T));
}

PACKED_STRUCT HCIPacket
{
    HCIPacketType type;

    union
    {
        PACKED_STRUCT
        {
            union __attribute__((packed))
            {
                uint16_t opcode;
                unsigned commandField : 10;
                unsigned groupField : 6;
            };

            uint8_t len;
            uint8_t data[0];
        }
        CommandPacket;
        PACKED_STRUCT
        {
            uint8_t eventCode;
            uint8_t len;
            uint8_t data[0];
        }
        EventPacket;
        PACKED_STRUCT
        {
            unsigned connectionHandle : 12;
            unsigned packetBoundaryFlags : 2;
            unsigned broadcastFlags : 2;
            uint16_t len;
            uint8_t data[0];
        }
        ACLDataPacket;
        PACKED_STRUCT
        {
            unsigned connectionHandle : 12;
            unsigned packetStatusFlags : 2;
            uint8_t len;
            uint8_t data[0];
        }
        SCODataPacket;
        PACKED_STRUCT
        {
            uint8_t LSB_opcode;
            uint8_t MSB_opcode;
            uint8_t LSB_len;
            uint8_t MSB_len;
            uint8_t data[0];
        }
        ExtendedCommandPacket;
    };
};

using RawHCIPacket = HCIPacket;